host: 0.0.0.0
port: 4001
url: http://wdrl.info
title: Web Development Reading List
description: A handcrafted, carefully selected list of web development related resources. Published usually every week.
permalink: /archive/:title
destination: _site
future: false
show_drafts: nil
markdown: redcarpet
safe: true
lsi: false
pygments: true
sass:
    syntax: scss        # scss|sass
    style:  compressed  # nested|expanded|compact|compressed
gems:
  - jekyll-sitemap
